# Generated from freedesktop.org.xml
class MimeMagic
  private
  EXTENSIONS = {
    '123' => 'application/vnd.lotus-1-2-3',
    '3ds' => 'image/x-3ds',
    '3g2' => 'video/3gpp',
    '3ga' => 'video/3gpp',
    '3gp' => 'video/3gpp',
    '3gpp' => 'video/3gpp',
    '602' => 'application/x-t602',
    '669' => 'audio/x-mod',
    '7z' => 'application/x-7z-compressed',
    'a' => 'application/x-archive',
    'aac' => 'audio/mp4',
    'abw' => 'application/x-abiword',
    'abw.crashed' => 'application/x-abiword',
    'abw.gz' => 'application/x-abiword',
    'ac3' => 'audio/ac3',
    'ace' => 'application/x-ace',
    'adb' => 'text/x-adasrc',
    'ads' => 'text/x-adasrc',
    'afm' => 'application/x-font-afm',
    'ag' => 'image/x-applix-graphics',
    'ai' => 'application/illustrator',
    'aif' => 'audio/x-aiff',
    'aifc' => 'audio/x-aiff',
    'aiff' => 'audio/x-aiff',
    'al' => 'application/x-perl',
    'alz' => 'application/x-alz',
    'amr' => 'audio/AMR',
    'ani' => 'application/x-navi-animation',
    'anx' => 'application/annodex',
    'ape' => 'audio/x-ape',
    'arj' => 'application/x-arj',
    'arw' => 'image/x-sony-arw',
    'as' => 'application/x-applix-spreadsheet',
    'asc' => 'application/pgp-encrypted',
    'asf' => 'video/x-ms-asf',
    'asp' => 'application/x-asp',
    'ass' => 'text/x-ssa',
    'asx' => 'audio/x-ms-asx',
    'atom' => 'application/atom+xml',
    'au' => 'audio/basic',
    'avi' => 'video/x-msvideo',
    'aw' => 'application/x-applix-word',
    'awb' => 'audio/AMR-WB',
    'awk' => 'application/x-awk',
    'axa' => 'audio/annodex',
    'axv' => 'video/annodex',
    'bak' => 'application/x-trash',
    'bcpio' => 'application/x-bcpio',
    'bdf' => 'application/x-font-bdf',
    'bib' => 'text/x-bibtex',
    'bin' => 'application/octet-stream',
    'blend' => 'application/x-blender',
    'blender' => 'application/x-blender',
    'bmp' => 'image/bmp',
    'bz' => 'application/x-bzip',
    'bz2' => 'application/x-bzip',
    'c' => 'text/x-c++src',
    'c++' => 'text/x-c++src',
    'cab' => 'application/vnd.ms-cab-compressed',
    'cb7' => 'application/x-cb7',
    'cbr' => 'application/x-cbr',
    'cbt' => 'application/x-cbt',
    'cbz' => 'application/x-cbz',
    'cc' => 'text/x-c++src',
    'cdf' => 'application/x-netcdf',
    'cdr' => 'application/vnd.corel-draw',
    'cer' => 'application/pkix-cert',
    'cert' => 'application/x-x509-ca-cert',
    'cgm' => 'image/cgm',
    'chm' => 'application/x-chm',
    'chrt' => 'application/x-kchart',
    'class' => 'application/x-java',
    'cls' => 'text/x-tex',
    'cmake' => 'text/x-cmake',
    'cpio' => 'application/x-cpio',
    'cpio.gz' => 'application/x-cpio-compressed',
    'cpp' => 'text/x-c++src',
    'cr2' => 'image/x-canon-cr2',
    'crl' => 'application/pkix-crl',
    'crt' => 'application/x-x509-ca-cert',
    'crw' => 'image/x-canon-crw',
    'cs' => 'text/x-csharp',
    'csh' => 'application/x-csh',
    'css' => 'text/css',
    'cssl' => 'text/css',
    'csv' => 'text/csv',
    'cue' => 'application/x-cue',
    'cur' => 'image/x-win-bitmap',
    'cxx' => 'text/x-c++src',
    'd' => 'text/x-dsrc',
    'dar' => 'application/x-dar',
    'dbf' => 'application/x-dbf',
    'dc' => 'application/x-dc-rom',
    'dcl' => 'text/x-dcl',
    'dcm' => 'application/dicom',
    'dcr' => 'image/x-kodak-dcr',
    'dds' => 'image/x-dds',
    'deb' => 'application/x-deb',
    'der' => 'application/x-x509-ca-cert',
    'desktop' => 'application/x-desktop',
    'dia' => 'application/x-dia-diagram',
    'diff' => 'text/x-patch',
    'divx' => 'video/x-msvideo',
    'djv' => 'image/vnd.djvu',
    'djvu' => 'image/vnd.djvu',
    'dng' => 'image/x-adobe-dng',
    'doc' => 'application/msword',
    'docbook' => 'application/docbook+xml',
    'docm' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'dot' => 'application/msword-template',
    'dsl' => 'text/x-dsl',
    'dtd' => 'application/xml-dtd',
    'dtx' => 'text/x-tex',
    'dv' => 'video/dv',
    'dvi' => 'application/x-dvi',
    'dvi.bz2' => 'application/x-bzdvi',
    'dvi.gz' => 'application/x-gzdvi',
    'dwg' => 'image/vnd.dwg',
    'dxf' => 'image/vnd.dxf',
    'e' => 'text/x-eiffel',
    'egon' => 'application/x-egon',
    'eif' => 'text/x-eiffel',
    'el' => 'text/x-emacs-lisp',
    'emf' => 'image/x-emf',
    'eml' => 'message/rfc822',
    'emp' => 'application/vnd.emusic-emusic_package',
    'ent' => 'application/xml-external-parsed-entity',
    'eps' => 'image/x-eps',
    'eps.bz2' => 'image/x-bzeps',
    'eps.gz' => 'image/x-gzeps',
    'epsf' => 'image/x-eps',
    'epsf.bz2' => 'image/x-bzeps',
    'epsf.gz' => 'image/x-gzeps',
    'epsi' => 'image/x-eps',
    'epsi.bz2' => 'image/x-bzeps',
    'epsi.gz' => 'image/x-gzeps',
    'epub' => 'application/epub+zip',
    'erl' => 'text/x-erlang',
    'es' => 'application/ecmascript',
    'etheme' => 'application/x-e-theme',
    'etx' => 'text/x-setext',
    'exe' => 'application/x-ms-dos-executable',
    'exr' => 'image/x-exr',
    'ez' => 'application/andrew-inset',
    'f' => 'text/x-fortran',
    'f90' => 'text/x-fortran',
    'f95' => 'text/x-fortran',
    'fb2' => 'application/x-fictionbook+xml',
    'fig' => 'image/x-xfig',
    'fits' => 'image/fits',
    'fl' => 'application/x-fluid',
    'flac' => 'audio/x-flac',
    'flc' => 'video/x-flic',
    'fli' => 'video/x-flic',
    'flv' => 'video/x-flv',
    'flw' => 'application/x-kivio',
    'fo' => 'text/x-xslfo',
    'fodg' => 'application/vnd.oasis.opendocument.graphics-flat-xml',
    'fodp' => 'application/vnd.oasis.opendocument.presentation-flat-xml',
    'fods' => 'application/vnd.oasis.opendocument.spreadsheet-flat-xml',
    'fodt' => 'application/vnd.oasis.opendocument.text-flat-xml',
    'for' => 'text/x-fortran',
    'g3' => 'image/fax-g3',
    'gb' => 'application/x-gameboy-rom',
    'gba' => 'application/x-gba-rom',
    'gcrd' => 'text/directory',
    'ged' => 'application/x-gedcom',
    'gedcom' => 'application/x-gedcom',
    'gen' => 'application/x-genesis-rom',
    'gf' => 'application/x-tex-gf',
    'gg' => 'application/x-sms-rom',
    'gif' => 'image/gif',
    'glade' => 'application/x-glade',
    'gmo' => 'application/x-gettext-translation',
    'gnc' => 'application/x-gnucash',
    'gnd' => 'application/gnunet-directory',
    'gnucash' => 'application/x-gnucash',
    'gnumeric' => 'application/x-gnumeric',
    'gnuplot' => 'application/x-gnuplot',
    'gp' => 'application/x-gnuplot',
    'gpg' => 'application/pgp-encrypted',
    'gplt' => 'application/x-gnuplot',
    'gra' => 'application/x-graphite',
    'gsf' => 'application/x-font-type1',
    'gsm' => 'audio/x-gsm',
    'gtar' => 'application/x-tar',
    'gv' => 'text/vnd.graphviz',
    'gvp' => 'text/x-google-video-pointer',
    'gz' => 'application/x-gzip',
    'h' => 'text/x-chdr',
    'h++' => 'text/x-c++hdr',
    'hdf' => 'application/x-hdf',
    'hh' => 'text/x-c++hdr',
    'hp' => 'text/x-c++hdr',
    'hpgl' => 'application/vnd.hp-hpgl',
    'hpp' => 'text/x-c++hdr',
    'hs' => 'text/x-haskell',
    'htm' => 'text/html',
    'html' => 'text/html',
    'hwp' => 'application/x-hwp',
    'hwt' => 'application/x-hwt',
    'hxx' => 'text/x-c++hdr',
    'ica' => 'application/x-ica',
    'icb' => 'image/x-tga',
    'icc' => 'application/vnd.iccprofile',
    'icm' => 'application/vnd.iccprofile',
    'icns' => 'image/x-icns',
    'ico' => 'image/vnd.microsoft.icon',
    'ics' => 'text/calendar',
    'idl' => 'text/x-idl',
    'ief' => 'image/ief',
    'iff' => 'image/x-iff',
    'ilbm' => 'image/x-ilbm',
    'ime' => 'text/x-iMelody',
    'imy' => 'text/x-iMelody',
    'ins' => 'text/x-tex',
    'iptables' => 'text/x-iptables',
    'iso' => 'application/x-cd-image',
    'iso9660' => 'application/x-cd-image',
    'it' => 'audio/x-it',
    'it87' => 'application/x-it87',
    'j2k' => 'image/jp2',
    'jad' => 'text/vnd.sun.j2me.app-descriptor',
    'jar' => 'application/x-java-archive',
    'java' => 'text/x-java',
    'jceks' => 'application/x-java-jce-keystore',
    'jks' => 'application/x-java-keystore',
    'jng' => 'image/x-jng',
    'jnlp' => 'application/x-java-jnlp-file',
    'jp2' => 'image/jp2',
    'jpc' => 'image/jp2',
    'jpe' => 'image/jpeg',
    'jpeg' => 'image/jpeg',
    'jpf' => 'image/jp2',
    'jpg' => 'image/jpeg',
    'jpr' => 'application/x-jbuilder-project',
    'jpx' => 'application/x-jbuilder-project',
    'js' => 'application/javascript',
    'k25' => 'image/x-kodak-k25',
    'kar' => 'audio/midi',
    'karbon' => 'application/x-karbon',
    'kdc' => 'image/x-kodak-kdc',
    'kdelnk' => 'application/x-desktop',
    'kexi' => 'application/x-kexiproject-sqlite2',
    'kexic' => 'application/x-kexi-connectiondata',
    'kexis' => 'application/x-kexiproject-shortcut',
    'kfo' => 'application/x-kformula',
    'kil' => 'application/x-killustrator',
    'kino' => 'application/smil',
    'kml' => 'application/vnd.google-earth.kml+xml',
    'kmz' => 'application/vnd.google-earth.kmz',
    'kon' => 'application/x-kontour',
    'kpm' => 'application/x-kpovmodeler',
    'kpr' => 'application/x-kpresenter',
    'kpt' => 'application/x-kpresenter',
    'kra' => 'application/x-krita',
    'ks' => 'application/x-java-keystore',
    'ksp' => 'application/x-kspread',
    'kud' => 'application/x-kugar',
    'kwd' => 'application/x-kword',
    'kwt' => 'application/x-kword',
    'la' => 'application/x-shared-library-la',
    'latex' => 'text/x-tex',
    'ldif' => 'text/x-ldif',
    'lha' => 'application/x-lha',
    'lhs' => 'text/x-literate-haskell',
    'lhz' => 'application/x-lhz',
    'log' => 'text/x-log',
    'ltx' => 'text/x-tex',
    'lua' => 'text/x-lua',
    'lwo' => 'image/x-lwo',
    'lwob' => 'image/x-lwo',
    'lws' => 'image/x-lws',
    'ly' => 'text/x-lilypond',
    'lyx' => 'application/x-lyx',
    'lz' => 'application/x-lzip',
    'lzh' => 'application/x-lha',
    'lzma' => 'application/x-lzma',
    'lzo' => 'application/x-lzop',
    'm' => 'text/x-objcsrc',
    'm15' => 'audio/x-mod',
    'm2t' => 'video/mpeg',
    'm3u' => 'audio/x-mpegurl',
    'm3u8' => 'audio/x-mpegurl',
    'm4' => 'application/x-m4',
    'm4a' => 'audio/mp4',
    'm4b' => 'audio/x-m4b',
    'm4v' => 'video/mp4',
    'mab' => 'application/x-markaby',
    'man' => 'application/x-troff-man',
    'mbox' => 'application/mbox',
    'md' => 'application/x-genesis-rom',
    'mdb' => 'application/vnd.ms-access',
    'mdi' => 'image/vnd.ms-modi',
    'me' => 'text/x-troff-me',
    'med' => 'audio/x-mod',
    'metalink' => 'application/metalink+xml',
    'mgp' => 'application/x-magicpoint',
    'mid' => 'audio/midi',
    'midi' => 'audio/midi',
    'mif' => 'application/x-mif',
    'minipsf' => 'audio/x-minipsf',
    'mka' => 'audio/x-matroska',
    'mkv' => 'video/x-matroska',
    'ml' => 'text/x-ocaml',
    'mli' => 'text/x-ocaml',
    'mm' => 'text/x-troff-mm',
    'mmf' => 'application/x-smaf',
    'mml' => 'application/mathml+xml',
    'mng' => 'video/x-mng',
    'mo' => 'application/x-gettext-translation',
    'mo3' => 'audio/x-mo3',
    'moc' => 'text/x-moc',
    'mod' => 'audio/x-mod',
    'mof' => 'text/x-mof',
    'moov' => 'video/quicktime',
    'mov' => 'video/quicktime',
    'movie' => 'video/x-sgi-movie',
    'mp+' => 'audio/x-musepack',
    'mp2' => 'audio/mp2',
    'mp3' => 'audio/mpeg',
    'mp4' => 'video/mp4',
    'mpc' => 'audio/x-musepack',
    'mpe' => 'video/mpeg',
    'mpeg' => 'video/mpeg',
    'mpg' => 'video/mpeg',
    'mpga' => 'audio/mpeg',
    'mpp' => 'audio/x-musepack',
    'mrl' => 'text/x-mrml',
    'mrml' => 'text/x-mrml',
    'mrw' => 'image/x-minolta-mrw',
    'ms' => 'text/x-troff-ms',
    'msi' => 'application/x-msi',
    'msod' => 'image/x-msod',
    'msx' => 'application/x-msx-rom',
    'mtm' => 'audio/x-mod',
    'mup' => 'text/x-mup',
    'mxf' => 'application/mxf',
    'n64' => 'application/x-n64-rom',
    'nb' => 'application/mathematica',
    'nc' => 'application/x-netcdf',
    'nds' => 'application/x-nintendo-ds-rom',
    'nef' => 'image/x-nikon-nef',
    'nes' => 'application/x-nes-rom',
    'nfo' => 'text/x-nfo',
    'not' => 'text/x-mup',
    'nsc' => 'application/x-netshow-channel',
    'nsv' => 'video/x-nsv',
    'o' => 'application/x-object',
    'obj' => 'application/x-tgif',
    'ocl' => 'text/x-ocl',
    'oda' => 'application/oda',
    'odb' => 'application/vnd.oasis.opendocument.database',
    'odc' => 'application/vnd.oasis.opendocument.chart',
    'odf' => 'application/vnd.oasis.opendocument.formula',
    'odg' => 'application/vnd.oasis.opendocument.graphics',
    'odi' => 'application/vnd.oasis.opendocument.image',
    'odm' => 'application/vnd.oasis.opendocument.text-master',
    'odp' => 'application/vnd.oasis.opendocument.presentation',
    'ods' => 'application/vnd.oasis.opendocument.spreadsheet',
    'odt' => 'application/vnd.oasis.opendocument.text',
    'oga' => 'audio/ogg',
    'ogg' => 'audio/ogg',
    'ogm' => 'video/x-ogm+ogg',
    'ogv' => 'video/ogg',
    'ogx' => 'application/ogg',
    'old' => 'application/x-trash',
    'oleo' => 'application/x-oleo',
    'opml' => 'text/x-opml+xml',
    'ora' => 'image/openraster',
    'orf' => 'image/x-olympus-orf',
    'otc' => 'application/vnd.oasis.opendocument.chart-template',
    'otf' => 'application/vnd.oasis.opendocument.formula-template',
    'otg' => 'application/vnd.oasis.opendocument.graphics-template',
    'oth' => 'application/vnd.oasis.opendocument.text-web',
    'otp' => 'application/vnd.oasis.opendocument.presentation-template',
    'ots' => 'application/vnd.oasis.opendocument.spreadsheet-template',
    'ott' => 'application/vnd.oasis.opendocument.text-template',
    'owl' => 'application/rdf+xml',
    'oxt' => 'application/vnd.openofficeorg.extension',
    'p' => 'text/x-pascal',
    'p10' => 'application/pkcs10',
    'p12' => 'application/x-pkcs12',
    'p7b' => 'application/x-pkcs7-certificates',
    'p7s' => 'application/pkcs7-signature',
    'pack' => 'application/x-java-pack200',
    'pak' => 'application/x-pak',
    'par2' => 'application/x-par2',
    'pas' => 'text/x-pascal',
    'patch' => 'text/x-patch',
    'pbm' => 'image/x-portable-bitmap',
    'pcd' => 'image/x-photo-cd',
    'pcf' => 'application/x-font-pcf',
    'pcf.gz' => 'application/x-font-pcf',
    'pcf.z' => 'application/x-font-pcf',
    'pcl' => 'application/vnd.hp-pcl',
    'pcx' => 'image/x-pcx',
    'pdb' => 'application/x-aportisdoc',
    'pdc' => 'application/x-aportisdoc',
    'pdf' => 'application/pdf',
    'pdf.bz2' => 'application/x-bzpdf',
    'pdf.gz' => 'application/x-gzpdf',
    'pef' => 'image/x-pentax-pef',
    'pem' => 'application/x-x509-ca-cert',
    'perl' => 'application/x-perl',
    'pfa' => 'application/x-font-type1',
    'pfb' => 'application/x-font-type1',
    'pfx' => 'application/x-pkcs12',
    'pgm' => 'image/x-portable-graymap',
    'pgn' => 'application/x-chess-pgn',
    'pgp' => 'application/pgp-encrypted',
    'php' => 'application/x-php',
    'php3' => 'application/x-php',
    'php4' => 'application/x-php',
    'pict' => 'image/x-pict',
    'pict1' => 'image/x-pict',
    'pict2' => 'image/x-pict',
    'pk' => 'application/x-tex-pk',
    'pkipath' => 'application/pkix-pkipath',
    'pkr' => 'application/pgp-keys',
    'pl' => 'application/x-perl',
    'pla' => 'audio/x-iriver-pla',
    'pln' => 'application/x-planperfect',
    'pls' => 'audio/x-scpls',
    'pm' => 'application/x-perl',
    'png' => 'image/png',
    'pnm' => 'image/x-portable-anymap',
    'pntg' => 'image/x-macpaint',
    'po' => 'text/x-gettext-translation',
    'por' => 'application/x-spss-por',
    'pot' => 'application/vnd.ms-powerpoint',
    'ppm' => 'image/x-portable-pixmap',
    'pps' => 'application/vnd.ms-powerpoint',
    'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'ppt' => 'application/vnd.ms-powerpoint',
    'pptm' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'ppz' => 'application/vnd.ms-powerpoint',
    'prc' => 'application/x-palm-database',
    'ps' => 'application/postscript',
    'ps.bz2' => 'application/x-bzpostscript',
    'ps.gz' => 'application/x-gzpostscript',
    'psd' => 'image/vnd.adobe.photoshop',
    'psf' => 'application/x-font-linux-psf',
    'psf.gz' => 'application/x-gz-font-linux-psf',
    'psflib' => 'audio/x-psflib',
    'psid' => 'audio/prs.sid',
    'psw' => 'application/x-pocket-word',
    'pw' => 'application/x-pw',
    'py' => 'text/x-python',
    'pyc' => 'application/x-python-bytecode',
    'pyo' => 'application/x-python-bytecode',
    'qif' => 'application/x-qw',
    'qt' => 'video/quicktime',
    'qtif' => 'image/x-quicktime',
    'qtl' => 'application/x-quicktime-media-link',
    'qtvr' => 'video/quicktime',
    'ra' => 'audio/vnd.rn-realaudio',
    'raf' => 'image/x-fuji-raf',
    'ram' => 'application/ram',
    'rar' => 'application/x-rar',
    'ras' => 'image/x-cmu-raster',
    'raw' => 'image/x-panasonic-raw',
    'rax' => 'audio/vnd.rn-realaudio',
    'rb' => 'application/x-ruby',
    'rdf' => 'application/rdf+xml',
    'rdfs' => 'application/rdf+xml',
    'reg' => 'text/x-ms-regedit',
    'rej' => 'application/x-reject',
    'rgb' => 'image/x-rgb',
    'rle' => 'image/rle',
    'rm' => 'application/vnd.rn-realmedia',
    'rmj' => 'application/vnd.rn-realmedia',
    'rmm' => 'application/vnd.rn-realmedia',
    'rms' => 'application/vnd.rn-realmedia',
    'rmvb' => 'application/vnd.rn-realmedia',
    'rmx' => 'application/vnd.rn-realmedia',
    'roff' => 'text/troff',
    'rp' => 'image/vnd.rn-realpix',
    'rpm' => 'application/x-rpm',
    'rss' => 'application/rss+xml',
    'rt' => 'text/vnd.rn-realtext',
    'rtf' => 'application/rtf',
    'rtx' => 'text/richtext',
    'rv' => 'video/vnd.rn-realvideo',
    'rvx' => 'video/vnd.rn-realvideo',
    's3m' => 'audio/x-s3m',
    'sam' => 'application/x-amipro',
    'sami' => 'application/x-sami',
    'sav' => 'application/x-spss-sav',
    'scm' => 'text/x-scheme',
    'sda' => 'application/vnd.stardivision.draw',
    'sdc' => 'application/vnd.stardivision.calc',
    'sdd' => 'application/vnd.stardivision.impress',
    'sdp' => 'application/vnd.stardivision.impress',
    'sds' => 'application/vnd.stardivision.chart',
    'sdw' => 'application/vnd.stardivision.writer',
    'sgf' => 'application/x-go-sgf',
    'sgi' => 'image/x-sgi',
    'sgl' => 'application/vnd.stardivision.writer',
    'sgm' => 'text/sgml',
    'sgml' => 'text/sgml',
    'sh' => 'application/x-shellscript',
    'shar' => 'application/x-shar',
    'shn' => 'application/x-shorten',
    'siag' => 'application/x-siag',
    'sid' => 'audio/prs.sid',
    'sik' => 'application/x-trash',
    'sis' => 'application/vnd.symbian.install',
    'sisx' => 'x-epoc/x-sisx-app',
    'sit' => 'application/x-stuffit',
    'siv' => 'application/sieve',
    'sk' => 'image/x-skencil',
    'sk1' => 'image/x-skencil',
    'skr' => 'application/pgp-keys',
    'slk' => 'text/spreadsheet',
    'smaf' => 'application/x-smaf',
    'smc' => 'application/x-snes-rom',
    'smd' => 'application/vnd.stardivision.mail',
    'smf' => 'application/vnd.stardivision.math',
    'smi' => 'application/smil',
    'smil' => 'application/smil',
    'sml' => 'application/smil',
    'sms' => 'application/x-sms-rom',
    'snd' => 'audio/basic',
    'so' => 'application/x-sharedlib',
    'spc' => 'application/x-pkcs7-certificates',
    'spd' => 'application/x-font-speedo',
    'spec' => 'text/x-rpm-spec',
    'spl' => 'application/x-shockwave-flash',
    'spx' => 'audio/ogg',
    'sql' => 'text/x-sql',
    'sr2' => 'image/x-sony-sr2',
    'src' => 'application/x-wais-source',
    'srf' => 'image/x-sony-srf',
    'srt' => 'application/x-subrip',
    'ssa' => 'text/x-ssa',
    'stc' => 'application/vnd.sun.xml.calc.template',
    'std' => 'application/vnd.sun.xml.draw.template',
    'sti' => 'application/vnd.sun.xml.impress.template',
    'stm' => 'audio/x-stm',
    'stw' => 'application/vnd.sun.xml.writer.template',
    'sty' => 'text/x-tex',
    'sub' => 'text/x-microdvd',
    'sun' => 'image/x-sun-raster',
    'sv4cpio' => 'application/x-sv4cpio',
    'sv4crc' => 'application/x-sv4crc',
    'svg' => 'image/svg+xml',
    'svgz' => 'image/svg+xml-compressed',
    'swf' => 'application/x-shockwave-flash',
    'sxc' => 'application/vnd.sun.xml.calc',
    'sxd' => 'application/vnd.sun.xml.draw',
    'sxg' => 'application/vnd.sun.xml.writer.global',
    'sxi' => 'application/vnd.sun.xml.impress',
    'sxm' => 'application/vnd.sun.xml.math',
    'sxw' => 'application/vnd.sun.xml.writer',
    'sylk' => 'text/spreadsheet',
    't' => 'text/troff',
    't2t' => 'text/x-txt2tags',
    'tar' => 'application/x-tar',
    'tar.bz' => 'application/x-bzip-compressed-tar',
    'tar.bz2' => 'application/x-bzip-compressed-tar',
    'tar.gz' => 'application/x-compressed-tar',
    'tar.lzma' => 'application/x-lzma-compressed-tar',
    'tar.lzo' => 'application/x-tzo',
    'tar.xz' => 'application/x-xz-compressed-tar',
    'tar.z' => 'application/x-tarz',
    'tbz' => 'application/x-bzip-compressed-tar',
    'tbz2' => 'application/x-bzip-compressed-tar',
    'tcl' => 'text/x-tcl',
    'tex' => 'text/x-tex',
    'texi' => 'text/x-texinfo',
    'texinfo' => 'text/x-texinfo',
    'tga' => 'image/x-tga',
    'tgz' => 'application/x-compressed-tar',
    'theme' => 'application/x-theme',
    'themepack' => 'application/x-windows-themepack',
    'tif' => 'image/tiff',
    'tiff' => 'image/tiff',
    'tk' => 'text/x-tcl',
    'tlz' => 'application/x-lzma-compressed-tar',
    'tnef' => 'application/vnd.ms-tnef',
    'tnf' => 'application/vnd.ms-tnef',
    'toc' => 'application/x-cdrdao-toc',
    'torrent' => 'application/x-bittorrent',
    'tpic' => 'image/x-tga',
    'tr' => 'text/troff',
    'ts' => 'application/x-linguist',
    'tsv' => 'text/tab-separated-values',
    'tta' => 'audio/x-tta',
    'ttc' => 'application/x-font-ttf',
    'ttf' => 'application/x-font-ttf',
    'ttx' => 'application/x-font-ttx',
    'txt' => 'text/plain',
    'txz' => 'application/x-xz-compressed-tar',
    'tzo' => 'application/x-tzo',
    'ufraw' => 'application/x-ufraw',
    'ui' => 'application/x-designer',
    'uil' => 'text/x-uil',
    'ult' => 'audio/x-mod',
    'uni' => 'audio/x-mod',
    'uri' => 'text/x-uri',
    'url' => 'text/x-uri',
    'ustar' => 'application/x-ustar',
    'vala' => 'text/x-vala',
    'vapi' => 'text/x-vala',
    'vcf' => 'text/directory',
    'vcs' => 'text/calendar',
    'vct' => 'text/directory',
    'vda' => 'image/x-tga',
    'vhd' => 'text/x-vhdl',
    'vhdl' => 'text/x-vhdl',
    'viv' => 'video/vivo',
    'vivo' => 'video/vivo',
    'vlc' => 'audio/x-mpegurl',
    'vob' => 'video/mpeg',
    'voc' => 'audio/x-voc',
    'vor' => 'application/vnd.stardivision.writer',
    'vst' => 'image/x-tga',
    'wav' => 'audio/x-wav',
    'wax' => 'audio/x-ms-asx',
    'wb1' => 'application/x-quattropro',
    'wb2' => 'application/x-quattropro',
    'wb3' => 'application/x-quattropro',
    'wbmp' => 'image/vnd.wap.wbmp',
    'wcm' => 'application/vnd.ms-works',
    'wdb' => 'application/vnd.ms-works',
    'wk1' => 'application/vnd.lotus-1-2-3',
    'wk3' => 'application/vnd.lotus-1-2-3',
    'wk4' => 'application/vnd.lotus-1-2-3',
    'wks' => 'application/vnd.lotus-1-2-3',
    'wma' => 'audio/x-ms-wma',
    'wmf' => 'image/x-wmf',
    'wml' => 'text/vnd.wap.wml',
    'wmls' => 'text/vnd.wap.wmlscript',
    'wmv' => 'video/x-ms-wmv',
    'wmx' => 'audio/x-ms-asx',
    'wp' => 'application/vnd.wordperfect',
    'wp4' => 'application/vnd.wordperfect',
    'wp5' => 'application/vnd.wordperfect',
    'wp6' => 'application/vnd.wordperfect',
    'wpd' => 'application/vnd.wordperfect',
    'wpg' => 'application/x-wpg',
    'wpl' => 'application/vnd.ms-wpl',
    'wpp' => 'application/vnd.wordperfect',
    'wps' => 'application/vnd.ms-works',
    'wri' => 'application/x-mswrite',
    'wrl' => 'model/vrml',
    'wv' => 'audio/x-wavpack',
    'wvc' => 'audio/x-wavpack-correction',
    'wvp' => 'audio/x-wavpack',
    'wvx' => 'audio/x-ms-asx',
    'x3f' => 'image/x-sigma-x3f',
    'xac' => 'application/x-gnucash',
    'xbel' => 'application/x-xbel',
    'xbl' => 'application/xml',
    'xbm' => 'image/x-xbitmap',
    'xcf' => 'image/x-xcf',
    'xcf.bz2' => 'image/x-compressed-xcf',
    'xcf.gz' => 'image/x-compressed-xcf',
    'xhtml' => 'application/xhtml+xml',
    'xi' => 'audio/x-xi',
    'xla' => 'application/vnd.ms-excel',
    'xlc' => 'application/vnd.ms-excel',
    'xld' => 'application/vnd.ms-excel',
    'xlf' => 'application/x-xliff',
    'xliff' => 'application/x-xliff',
    'xll' => 'application/vnd.ms-excel',
    'xlm' => 'application/vnd.ms-excel',
    'xls' => 'application/vnd.ms-excel',
    'xlsm' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xlt' => 'application/vnd.ms-excel',
    'xlw' => 'application/vnd.ms-excel',
    'xm' => 'audio/x-xm',
    'xmf' => 'audio/x-xmf',
    'xmi' => 'text/x-xmi',
    'xml' => 'application/xml',
    'xpm' => 'image/x-xpixmap',
    'xps' => 'application/vnd.ms-xpsdocument',
    'xsl' => 'application/xslt+xml',
    'xslfo' => 'text/x-xslfo',
    'xslt' => 'application/xslt+xml',
    'xspf' => 'application/xspf+xml',
    'xul' => 'application/vnd.mozilla.xul+xml',
    'xwd' => 'image/x-xwindowdump',
    'xz' => 'application/x-xz',
    'z' => 'application/x-compress',
    'zabw' => 'application/x-abiword',
    'zip' => 'application/zip',
    'zoo' => 'application/x-zoo',
  }
  TYPES = {
    'application/andrew-inset' => [%w(ez), %w()],
    'application/annodex' => [%w(anx), %w()],
    'application/atom+xml' => [%w(atom), %w(application/xml)],
    'application/dicom' => [%w(dcm), %w()],
    'application/docbook+xml' => [%w(docbook), %w(application/xml)],
    'application/ecmascript' => [%w(es), %w(text/plain)],
    'application/epub+zip' => [%w(epub), %w()],
    'application/gnunet-directory' => [%w(gnd), %w()],
    'application/illustrator' => [%w(ai), %w()],
    'application/javascript' => [%w(js), %w(text/x-csrc)],
    'application/mathematica' => [%w(nb), %w(text/plain)],
    'application/mathml+xml' => [%w(mml), %w(application/xml)],
    'application/mbox' => [%w(mbox), %w(text/plain)],
    'application/metalink+xml' => [%w(metalink), %w(application/xml)],
    'application/msword' => [%w(doc), %w(application/x-ole-storage)],
    'application/msword-template' => [%w(dot), %w(application/msword)],
    'application/mxf' => [%w(mxf), %w()],
    'application/octet-stream' => [%w(bin), %w()],
    'application/oda' => [%w(oda), %w()],
    'application/ogg' => [%w(ogx), %w()],
    'application/pdf' => [%w(pdf), %w()],
    'application/pgp-encrypted' => [%w(asc gpg pgp), %w()],
    'application/pgp-keys' => [%w(asc pkr skr), %w(text/plain)],
    'application/pkcs10' => [%w(p10), %w()],
    'application/pkcs7-signature' => [%w(p7s), %w(text/plain)],
    'application/pkix-cert' => [%w(cer), %w()],
    'application/pkix-crl' => [%w(crl), %w()],
    'application/pkix-pkipath' => [%w(pkipath), %w()],
    'application/postscript' => [%w(ps), %w(text/plain)],
    'application/ram' => [%w(ram), %w(text/plain)],
    'application/rdf+xml' => [%w(owl rdf rdfs), %w(application/xml)],
    'application/rss+xml' => [%w(rss), %w(application/xml)],
    'application/rtf' => [%w(rtf), %w(text/plain)],
    'application/sdp' => [%w(sdp), %w()],
    'application/sieve' => [%w(siv), %w(application/xml)],
    'application/smil' => [%w(kino smi smil sml), %w(application/xml)],
    'application/vnd.apple.mpegurl' => [%w(m3u m3u8), %w()],
    'application/vnd.corel-draw' => [%w(cdr), %w()],
    'application/vnd.emusic-emusic_package' => [%w(emp), %w()],
    'application/vnd.google-earth.kml+xml' => [%w(kml), %w(application/xml)],
    'application/vnd.google-earth.kmz' => [%w(kmz), %w(application/zip)],
    'application/vnd.hp-hpgl' => [%w(hpgl), %w()],
    'application/vnd.hp-pcl' => [%w(pcl), %w()],
    'application/vnd.iccprofile' => [%w(icc icm), %w()],
    'application/vnd.lotus-1-2-3' => [%w(123 wk1 wk3 wk4 wks), %w()],
    'application/vnd.mozilla.xul+xml' => [%w(xul), %w(application/xml)],
    'application/vnd.ms-access' => [%w(mdb), %w()],
    'application/vnd.ms-cab-compressed' => [%w(cab), %w()],
    'application/vnd.ms-excel' => [%w(xla xlc xld xll xlm xls xlt xlw), %w()],
    'application/vnd.ms-powerpoint' => [%w(pot pps ppt ppz), %w()],
    'application/vnd.ms-tnef' => [%w(tnef tnf), %w()],
    'application/vnd.ms-works' => [%w(wcm wdb wks wps), %w(application/x-ole-storage)],
    'application/vnd.ms-wpl' => [%w(wpl), %w()],
    'application/vnd.ms-xpsdocument' => [%w(xps), %w(application/zip)],
    'application/vnd.oasis.opendocument.chart' => [%w(odc), %w(application/zip)],
    'application/vnd.oasis.opendocument.chart-template' => [%w(otc), %w(application/zip)],
    'application/vnd.oasis.opendocument.database' => [%w(odb), %w(application/zip)],
    'application/vnd.oasis.opendocument.formula' => [%w(odf), %w(application/zip)],
    'application/vnd.oasis.opendocument.formula-template' => [%w(otf), %w(application/zip)],
    'application/vnd.oasis.opendocument.graphics' => [%w(odg), %w(application/zip)],
    'application/vnd.oasis.opendocument.graphics-flat-xml' => [%w(fodg), %w(application/xml)],
    'application/vnd.oasis.opendocument.graphics-template' => [%w(otg), %w(application/zip)],
    'application/vnd.oasis.opendocument.image' => [%w(odi), %w(application/zip)],
    'application/vnd.oasis.opendocument.presentation' => [%w(odp), %w(application/zip)],
    'application/vnd.oasis.opendocument.presentation-flat-xml' => [%w(fodp), %w(application/xml)],
    'application/vnd.oasis.opendocument.presentation-template' => [%w(otp), %w(application/zip)],
    'application/vnd.oasis.opendocument.spreadsheet' => [%w(ods), %w(application/zip)],
    'application/vnd.oasis.opendocument.spreadsheet-flat-xml' => [%w(fods), %w(application/xml)],
    'application/vnd.oasis.opendocument.spreadsheet-template' => [%w(ots), %w(application/zip)],
    'application/vnd.oasis.opendocument.text' => [%w(odt), %w(application/zip)],
    'application/vnd.oasis.opendocument.text-flat-xml' => [%w(fodt), %w(application/xml)],
    'application/vnd.oasis.opendocument.text-master' => [%w(odm), %w(application/zip)],
    'application/vnd.oasis.opendocument.text-template' => [%w(ott), %w(application/zip)],
    'application/vnd.oasis.opendocument.text-web' => [%w(oth), %w(application/zip)],
    'application/vnd.openofficeorg.extension' => [%w(oxt), %w(application/zip)],
    'application/vnd.openxmlformats-officedocument.presentationml.presentation' => [%w(pptm pptx), %w(application/zip)],
    'application/vnd.openxmlformats-officedocument.presentationml.slideshow' => [%w(ppsx), %w(application/zip)],
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' => [%w(xlsm xlsx), %w(application/zip)],
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document' => [%w(docm docx), %w(application/zip)],
    'application/vnd.rn-realmedia' => [%w(rm rmj rmm rms rmvb rmx), %w()],
    'application/vnd.stardivision.calc' => [%w(sdc), %w()],
    'application/vnd.stardivision.chart' => [%w(sds), %w()],
    'application/vnd.stardivision.draw' => [%w(sda), %w()],
    'application/vnd.stardivision.impress' => [%w(sdd sdp), %w()],
    'application/vnd.stardivision.mail' => [%w(smd), %w()],
    'application/vnd.stardivision.math' => [%w(smf), %w()],
    'application/vnd.stardivision.writer' => [%w(sdw sgl vor), %w()],
    'application/vnd.sun.xml.calc' => [%w(sxc), %w(application/zip)],
    'application/vnd.sun.xml.calc.template' => [%w(stc), %w(application/zip)],
    'application/vnd.sun.xml.draw' => [%w(sxd), %w(application/zip)],
    'application/vnd.sun.xml.draw.template' => [%w(std), %w(application/zip)],
    'application/vnd.sun.xml.impress' => [%w(sxi), %w(application/zip)],
    'application/vnd.sun.xml.impress.template' => [%w(sti), %w(application/zip)],
    'application/vnd.sun.xml.math' => [%w(sxm), %w(application/zip)],
    'application/vnd.sun.xml.writer' => [%w(sxw), %w(application/zip)],
    'application/vnd.sun.xml.writer.global' => [%w(sxg), %w(application/zip)],
    'application/vnd.sun.xml.writer.template' => [%w(stw), %w(application/zip)],
    'application/vnd.symbian.install' => [%w(sis), %w()],
    'application/vnd.wordperfect' => [%w(wp wp4 wp5 wp6 wpd wpp), %w()],
    'application/x-7z-compressed' => [%w(7z), %w()],
    'application/x-abiword' => [%w(abw abw.crashed abw.gz zabw), %w(application/xml)],
    'application/x-ace' => [%w(ace), %w()],
    'application/x-alz' => [%w(alz), %w()],
    'application/x-amipro' => [%w(sam), %w()],
    'application/x-aportisdoc' => [%w(pdb pdc), %w(application/x-palm-database)],
    'application/x-applix-spreadsheet' => [%w(as), %w()],
    'application/x-applix-word' => [%w(aw), %w()],
    'application/x-archive' => [%w(a), %w()],
    'application/x-arj' => [%w(arj), %w()],
    'application/x-asp' => [%w(asp), %w(text/plain)],
    'application/x-awk' => [%w(awk), %w(application/x-executable text/plain)],
    'application/x-bcpio' => [%w(bcpio), %w()],
    'application/x-bittorrent' => [%w(torrent), %w()],
    'application/x-blender' => [%w(blend blend blender), %w()],
    'application/x-bzdvi' => [%w(dvi.bz2), %w()],
    'application/x-bzip' => [%w(bz bz2), %w()],
    'application/x-bzip-compressed-tar' => [%w(tar.bz tar.bz2 tbz tbz2), %w(application/x-bzip)],
    'application/x-bzpdf' => [%w(pdf.bz2), %w()],
    'application/x-bzpostscript' => [%w(ps.bz2), %w()],
    'application/x-cb7' => [%w(cb7), %w(application/x-7z-compressed)],
    'application/x-cbr' => [%w(cbr), %w(application/x-rar)],
    'application/x-cbt' => [%w(cbt), %w(application/x-tar)],
    'application/x-cbz' => [%w(cbz), %w(application/zip)],
    'application/x-cd-image' => [%w(iso iso9660), %w()],
    'application/x-cdrdao-toc' => [%w(toc), %w(text/plain)],
    'application/x-chess-pgn' => [%w(pgn), %w(text/plain)],
    'application/x-chm' => [%w(chm), %w()],
    'application/x-cisco-vpn-settings' => [%w(pcf), %w()],
    'application/x-compress' => [%w(z), %w()],
    'application/x-compressed-tar' => [%w(tar.gz tgz), %w()],
    'application/x-cpio' => [%w(cpio), %w()],
    'application/x-cpio-compressed' => [%w(cpio.gz), %w()],
    'application/x-csh' => [%w(csh), %w(application/x-shellscript text/plain)],
    'application/x-cue' => [%w(cue), %w(text/plain)],
    'application/x-dar' => [%w(dar), %w()],
    'application/x-dbf' => [%w(dbf), %w()],
    'application/x-dc-rom' => [%w(dc), %w()],
    'application/x-deb' => [%w(deb), %w()],
    'application/x-designer' => [%w(ui), %w()],
    'application/x-desktop' => [%w(desktop kdelnk), %w(text/plain)],
    'application/x-dia-diagram' => [%w(dia), %w(application/xml)],
    'application/x-dvi' => [%w(dvi), %w()],
    'application/x-e-theme' => [%w(etheme), %w()],
    'application/x-egon' => [%w(egon), %w()],
    'application/x-fictionbook+xml' => [%w(fb2), %w(application/xml)],
    'application/x-fluid' => [%w(fl), %w(text/plain)],
    'application/x-font-afm' => [%w(afm), %w()],
    'application/x-font-bdf' => [%w(bdf), %w()],
    'application/x-font-linux-psf' => [%w(psf), %w()],
    'application/x-font-otf' => [%w(otf), %w()],
    'application/x-font-pcf' => [%w(pcf pcf.gz pcf.z), %w()],
    'application/x-font-speedo' => [%w(spd), %w()],
    'application/x-font-ttf' => [%w(ttc ttf), %w()],
    'application/x-font-ttx' => [%w(ttx), %w(text/xml)],
    'application/x-font-type1' => [%w(gsf pfa pfb), %w(application/postscript)],
    'application/x-gameboy-rom' => [%w(gb), %w()],
    'application/x-gba-rom' => [%w(gba), %w()],
    'application/x-gedcom' => [%w(ged gedcom), %w()],
    'application/x-genesis-rom' => [%w(gen md), %w()],
    'application/x-gettext-translation' => [%w(gmo mo), %w()],
    'application/x-glade' => [%w(glade), %w(application/xml)],
    'application/x-gnucash' => [%w(gnc gnucash xac), %w()],
    'application/x-gnumeric' => [%w(gnumeric), %w()],
    'application/x-gnuplot' => [%w(gnuplot gp gplt), %w(text/plain)],
    'application/x-go-sgf' => [%w(sgf), %w(text/plain)],
    'application/x-graphite' => [%w(gra), %w()],
    'application/x-gz-font-linux-psf' => [%w(psf.gz), %w(application/x-gzip)],
    'application/x-gzdvi' => [%w(dvi.gz), %w(application/x-gzip)],
    'application/x-gzip' => [%w(gz), %w()],
    'application/x-gzpdf' => [%w(pdf.gz), %w(application/x-gzip)],
    'application/x-gzpostscript' => [%w(ps.gz), %w(application/x-gzip)],
    'application/x-hdf' => [%w(hdf), %w()],
    'application/x-hwp' => [%w(hwp), %w()],
    'application/x-hwt' => [%w(hwt), %w()],
    'application/x-ica' => [%w(ica), %w(text/plain)],
    'application/x-it87' => [%w(it87), %w(text/plain)],
    'application/x-java' => [%w(class), %w()],
    'application/x-java-archive' => [%w(jar), %w()],
    'application/x-java-jce-keystore' => [%w(jceks), %w()],
    'application/x-java-jnlp-file' => [%w(jnlp), %w(application/xml)],
    'application/x-java-keystore' => [%w(jks ks), %w()],
    'application/x-java-pack200' => [%w(pack), %w()],
    'application/x-jbuilder-project' => [%w(jpr jpx), %w()],
    'application/x-karbon' => [%w(karbon), %w()],
    'application/x-kchart' => [%w(chrt), %w()],
    'application/x-kexi-connectiondata' => [%w(kexic), %w()],
    'application/x-kexiproject-shortcut' => [%w(kexis), %w()],
    'application/x-kexiproject-sqlite2' => [%w(kexi), %w(application/x-sqlite2)],
    'application/x-kexiproject-sqlite3' => [%w(kexi), %w(application/x-sqlite3)],
    'application/x-kformula' => [%w(kfo), %w()],
    'application/x-killustrator' => [%w(kil), %w()],
    'application/x-kivio' => [%w(flw), %w()],
    'application/x-kontour' => [%w(kon), %w()],
    'application/x-kpovmodeler' => [%w(kpm), %w()],
    'application/x-kpresenter' => [%w(kpr kpt), %w()],
    'application/x-krita' => [%w(kra), %w()],
    'application/x-kspread' => [%w(ksp), %w()],
    'application/x-kugar' => [%w(kud), %w()],
    'application/x-kword' => [%w(kwd kwt), %w()],
    'application/x-lha' => [%w(lha lzh), %w()],
    'application/x-lhz' => [%w(lhz), %w()],
    'application/x-linguist' => [%w(ts), %w()],
    'application/x-lyx' => [%w(lyx), %w(text/plain)],
    'application/x-lzip' => [%w(lz), %w()],
    'application/x-lzma' => [%w(lzma), %w()],
    'application/x-lzma-compressed-tar' => [%w(tar.lzma tlz), %w()],
    'application/x-lzop' => [%w(lzo), %w()],
    'application/x-m4' => [%w(m4), %w(text/plain)],
    'application/x-magicpoint' => [%w(mgp), %w(text/plain)],
    'application/x-markaby' => [%w(mab), %w(application/x-ruby)],
    'application/x-mif' => [%w(mif), %w()],
    'application/x-ms-dos-executable' => [%w(exe), %w()],
    'application/x-msi' => [%w(msi), %w(application/x-ole-storage)],
    'application/x-mswrite' => [%w(wri), %w()],
    'application/x-msx-rom' => [%w(msx), %w()],
    'application/x-n64-rom' => [%w(n64), %w()],
    'application/x-navi-animation' => [%w(ani), %w()],
    'application/x-nes-rom' => [%w(nes), %w()],
    'application/x-netcdf' => [%w(cdf nc), %w()],
    'application/x-netshow-channel' => [%w(nsc), %w(video/x-ms-asf)],
    'application/x-nintendo-ds-rom' => [%w(nds), %w()],
    'application/x-object' => [%w(o), %w()],
    'application/x-oleo' => [%w(oleo), %w()],
    'application/x-pak' => [%w(pak), %w()],
    'application/x-palm-database' => [%w(pdb prc), %w()],
    'application/x-par2' => [%w(par2 par2), %w()],
    'application/x-perl' => [%w(al perl pl pm), %w(application/x-executable text/plain)],
    'application/x-php' => [%w(php php3 php4), %w(text/plain)],
    'application/x-pkcs12' => [%w(p12 pfx), %w()],
    'application/x-pkcs7-certificates' => [%w(p7b spc), %w()],
    'application/x-planperfect' => [%w(pln), %w()],
    'application/x-pocket-word' => [%w(psw), %w()],
    'application/x-pw' => [%w(pw), %w()],
    'application/x-python-bytecode' => [%w(pyc pyo), %w()],
    'application/x-quattropro' => [%w(wb1 wb2 wb3), %w()],
    'application/x-quicktime-media-link' => [%w(qtl), %w(video/quicktime)],
    'application/x-qw' => [%w(qif), %w()],
    'application/x-rar' => [%w(rar), %w()],
    'application/x-reject' => [%w(rej), %w(text/plain)],
    'application/x-rpm' => [%w(rpm), %w()],
    'application/x-ruby' => [%w(rb), %w(application/x-executable text/plain)],
    'application/x-sami' => [%w(sami smi), %w(text/plain)],
    'application/x-shar' => [%w(shar), %w()],
    'application/x-shared-library-la' => [%w(la), %w(text/plain)],
    'application/x-sharedlib' => [%w(so), %w()],
    'application/x-shellscript' => [%w(sh), %w(application/x-executable text/plain)],
    'application/x-shockwave-flash' => [%w(spl swf), %w()],
    'application/x-shorten' => [%w(shn), %w()],
    'application/x-siag' => [%w(siag), %w()],
    'application/x-smaf' => [%w(mmf smaf), %w()],
    'application/x-sms-rom' => [%w(gg sms), %w()],
    'application/x-snes-rom' => [%w(smc), %w()],
    'application/x-spss-por' => [%w(por), %w()],
    'application/x-spss-sav' => [%w(sav), %w()],
    'application/x-stuffit' => [%w(sit), %w()],
    'application/x-subrip' => [%w(srt), %w(text/plain)],
    'application/x-sv4cpio' => [%w(sv4cpio), %w()],
    'application/x-sv4crc' => [%w(sv4crc), %w()],
    'application/x-t602' => [%w(602), %w()],
    'application/x-tar' => [%w(gtar tar), %w()],
    'application/x-tarz' => [%w(tar.z), %w()],
    'application/x-tex-gf' => [%w(gf), %w()],
    'application/x-tex-pk' => [%w(pk), %w()],
    'application/x-tgif' => [%w(obj), %w()],
    'application/x-theme' => [%w(theme), %w(application/x-desktop)],
    'application/x-trash' => [%w(bak old sik), %w()],
    'application/x-troff-man' => [%w(man), %w(text/plain)],
    'application/x-tzo' => [%w(tar.lzo tzo), %w()],
    'application/x-ufraw' => [%w(ufraw), %w(text/xml)],
    'application/x-ustar' => [%w(ustar), %w()],
    'application/x-wais-source' => [%w(src), %w()],
    'application/x-windows-themepack' => [%w(themepack), %w(application/vnd.ms-cab-compressed)],
    'application/x-wpg' => [%w(wpg), %w()],
    'application/x-x509-ca-cert' => [%w(cert crt der pem), %w()],
    'application/x-xbel' => [%w(xbel), %w(application/xml)],
    'application/x-xliff' => [%w(xlf xliff), %w(application/xml)],
    'application/x-xz' => [%w(xz), %w()],
    'application/x-xz-compressed-tar' => [%w(tar.xz txz), %w()],
    'application/x-zoo' => [%w(zoo), %w()],
    'application/xhtml+xml' => [%w(xhtml), %w(application/xml)],
    'application/xml' => [%w(xbl xml), %w(text/plain)],
    'application/xml-dtd' => [%w(dtd), %w(text/plain)],
    'application/xml-external-parsed-entity' => [%w(ent), %w(application/xml)],
    'application/xslt+xml' => [%w(xsl xslt), %w(application/xml)],
    'application/xspf+xml' => [%w(xspf), %w(application/xml)],
    'application/zip' => [%w(zip), %w()],
    'audio/AMR' => [%w(amr), %w()],
    'audio/AMR-WB' => [%w(awb), %w()],
    'audio/ac3' => [%w(ac3), %w()],
    'audio/annodex' => [%w(axa), %w(application/annodex)],
    'audio/basic' => [%w(au snd), %w()],
    'audio/midi' => [%w(kar mid midi), %w()],
    'audio/mp2' => [%w(mp2), %w()],
    'audio/mp4' => [%w(aac m4a), %w()],
    'audio/mpeg' => [%w(mp3 mpga), %w()],
    'audio/ogg' => [%w(oga ogg spx), %w(application/ogg)],
    'audio/prs.sid' => [%w(psid sid), %w()],
    'audio/vnd.rn-realaudio' => [%w(ra rax), %w()],
    'audio/x-aiff' => [%w(aif aifc aiff), %w()],
    'audio/x-ape' => [%w(ape), %w()],
    'audio/x-flac' => [%w(flac), %w()],
    'audio/x-flac+ogg' => [%w(ogg), %w(audio/ogg)],
    'audio/x-gsm' => [%w(gsm), %w()],
    'audio/x-iriver-pla' => [%w(pla), %w()],
    'audio/x-it' => [%w(it), %w()],
    'audio/x-m4b' => [%w(m4b), %w(audio/mp4)],
    'audio/x-matroska' => [%w(mka), %w(application/x-matroska)],
    'audio/x-minipsf' => [%w(minipsf), %w(audio/x-psf)],
    'audio/x-mo3' => [%w(mo3), %w()],
    'audio/x-mod' => [%w(669 m15 med mod mtm ult uni), %w()],
    'audio/x-mpegurl' => [%w(m3u m3u8 vlc), %w(text/plain)],
    'audio/x-ms-asx' => [%w(asx wax wmx wvx), %w()],
    'audio/x-ms-wma' => [%w(wma), %w(video/x-ms-asf)],
    'audio/x-musepack' => [%w(mp+ mpc mpp), %w()],
    'audio/x-psf' => [%w(psf), %w()],
    'audio/x-psflib' => [%w(psflib), %w(audio/x-psf)],
    'audio/x-s3m' => [%w(s3m), %w()],
    'audio/x-scpls' => [%w(pls), %w()],
    'audio/x-speex' => [%w(spx), %w()],
    'audio/x-speex+ogg' => [%w(ogg), %w(audio/ogg)],
    'audio/x-stm' => [%w(stm), %w()],
    'audio/x-tta' => [%w(tta), %w()],
    'audio/x-voc' => [%w(voc), %w()],
    'audio/x-vorbis+ogg' => [%w(ogg), %w(audio/ogg)],
    'audio/x-wav' => [%w(wav), %w()],
    'audio/x-wavpack' => [%w(wv wvp), %w()],
    'audio/x-wavpack-correction' => [%w(wvc), %w()],
    'audio/x-xi' => [%w(xi), %w()],
    'audio/x-xm' => [%w(xm), %w()],
    'audio/x-xmf' => [%w(xmf), %w()],
    'image/bmp' => [%w(bmp), %w()],
    'image/cgm' => [%w(cgm), %w()],
    'image/fax-g3' => [%w(g3), %w()],
    'image/fits' => [%w(fits), %w()],
    'image/gif' => [%w(gif), %w()],
    'image/ief' => [%w(ief), %w()],
    'image/jp2' => [%w(j2k jp2 jpc jpf jpx), %w()],
    'image/jpeg' => [%w(jpe jpeg jpg), %w()],
    'image/openraster' => [%w(ora), %w()],
    'image/png' => [%w(png), %w()],
    'image/rle' => [%w(rle), %w()],
    'image/svg+xml' => [%w(svg), %w(application/xml)],
    'image/svg+xml-compressed' => [%w(svgz), %w(application/x-gzip)],
    'image/tiff' => [%w(tif tiff), %w()],
    'image/vnd.adobe.photoshop' => [%w(psd), %w()],
    'image/vnd.djvu' => [%w(djv djvu), %w()],
    'image/vnd.dwg' => [%w(dwg), %w()],
    'image/vnd.dxf' => [%w(dxf), %w()],
    'image/vnd.microsoft.icon' => [%w(ico), %w()],
    'image/vnd.ms-modi' => [%w(mdi), %w()],
    'image/vnd.rn-realpix' => [%w(rp), %w()],
    'image/vnd.wap.wbmp' => [%w(wbmp), %w()],
    'image/x-3ds' => [%w(3ds), %w()],
    'image/x-adobe-dng' => [%w(dng), %w(image/tiff image/x-dcraw)],
    'image/x-applix-graphics' => [%w(ag), %w()],
    'image/x-bzeps' => [%w(eps.bz2 epsf.bz2 epsi.bz2), %w()],
    'image/x-canon-cr2' => [%w(cr2), %w(image/tiff image/x-dcraw)],
    'image/x-canon-crw' => [%w(crw), %w(image/x-dcraw)],
    'image/x-cmu-raster' => [%w(ras), %w()],
    'image/x-compressed-xcf' => [%w(xcf.bz2 xcf.gz), %w()],
    'image/x-dds' => [%w(dds), %w()],
    'image/x-emf' => [%w(emf), %w()],
    'image/x-eps' => [%w(eps epsf epsi), %w(application/postscript)],
    'image/x-exr' => [%w(exr), %w()],
    'image/x-fuji-raf' => [%w(raf), %w(image/x-dcraw)],
    'image/x-gzeps' => [%w(eps.gz epsf.gz epsi.gz), %w()],
    'image/x-icns' => [%w(icns), %w()],
    'image/x-iff' => [%w(iff), %w()],
    'image/x-ilbm' => [%w(ilbm), %w()],
    'image/x-jng' => [%w(jng), %w()],
    'image/x-kodak-dcr' => [%w(dcr), %w(image/tiff image/x-dcraw)],
    'image/x-kodak-k25' => [%w(k25), %w(image/tiff image/x-dcraw)],
    'image/x-kodak-kdc' => [%w(kdc), %w(image/tiff image/x-dcraw)],
    'image/x-lwo' => [%w(lwo lwob), %w()],
    'image/x-lws' => [%w(lws), %w()],
    'image/x-macpaint' => [%w(pntg), %w()],
    'image/x-minolta-mrw' => [%w(mrw), %w(image/x-dcraw)],
    'image/x-msod' => [%w(msod), %w()],
    'image/x-nikon-nef' => [%w(nef), %w(image/tiff image/x-dcraw)],
    'image/x-olympus-orf' => [%w(orf), %w(image/x-dcraw)],
    'image/x-panasonic-raw' => [%w(raw), %w(image/x-dcraw)],
    'image/x-pcx' => [%w(pcx), %w()],
    'image/x-pentax-pef' => [%w(pef), %w(image/tiff image/x-dcraw)],
    'image/x-photo-cd' => [%w(pcd), %w()],
    'image/x-pict' => [%w(pict pict1 pict2), %w()],
    'image/x-portable-anymap' => [%w(pnm), %w()],
    'image/x-portable-bitmap' => [%w(pbm), %w(image/x-portable-anymap)],
    'image/x-portable-graymap' => [%w(pgm), %w(image/x-portable-anymap)],
    'image/x-portable-pixmap' => [%w(ppm), %w(image/x-portable-anymap)],
    'image/x-quicktime' => [%w(qif qtif), %w()],
    'image/x-rgb' => [%w(rgb), %w()],
    'image/x-sgi' => [%w(sgi), %w()],
    'image/x-sigma-x3f' => [%w(x3f), %w(image/x-dcraw)],
    'image/x-skencil' => [%w(sk sk1), %w()],
    'image/x-sony-arw' => [%w(arw), %w(image/tiff image/x-dcraw)],
    'image/x-sony-sr2' => [%w(sr2), %w(image/tiff image/x-dcraw)],
    'image/x-sony-srf' => [%w(srf), %w(image/tiff image/x-dcraw)],
    'image/x-sun-raster' => [%w(sun), %w()],
    'image/x-tga' => [%w(icb tga tpic vda vst), %w()],
    'image/x-win-bitmap' => [%w(cur), %w()],
    'image/x-wmf' => [%w(wmf), %w()],
    'image/x-xbitmap' => [%w(xbm), %w()],
    'image/x-xcf' => [%w(xcf), %w()],
    'image/x-xfig' => [%w(fig), %w()],
    'image/x-xpixmap' => [%w(xpm), %w()],
    'image/x-xwindowdump' => [%w(xwd), %w()],
    'message/rfc822' => [%w(eml), %w(text/plain)],
    'model/vrml' => [%w(wrl), %w(text/plain)],
    'text/calendar' => [%w(ics vcs), %w(text/plain)],
    'text/css' => [%w(css cssl), %w(text/x-csrc)],
    'text/csv' => [%w(csv), %w(text/plain)],
    'text/directory' => [%w(gcrd vcf vct), %w(text/plain)],
    'text/html' => [%w(htm html), %w(text/plain)],
    'text/plain' => [%w(asc txt), %w()],
    'text/richtext' => [%w(rtx), %w(text/plain)],
    'text/sgml' => [%w(sgm sgml), %w(text/plain)],
    'text/spreadsheet' => [%w(slk sylk), %w(text/plain)],
    'text/tab-separated-values' => [%w(tsv), %w(text/plain)],
    'text/troff' => [%w(roff t tr), %w(text/plain)],
    'text/vnd.graphviz' => [%w(dot gv), %w()],
    'text/vnd.rn-realtext' => [%w(rt), %w()],
    'text/vnd.sun.j2me.app-descriptor' => [%w(jad), %w()],
    'text/vnd.wap.wml' => [%w(wml), %w(application/xml)],
    'text/vnd.wap.wmlscript' => [%w(wmls), %w()],
    'text/x-adasrc' => [%w(adb ads), %w(text/plain)],
    'text/x-bibtex' => [%w(bib), %w(text/plain)],
    'text/x-c++hdr' => [%w(h++ hh hp hpp hxx), %w(text/x-chdr)],
    'text/x-c++src' => [%w(c c++ cc cpp cxx), %w(text/x-csrc)],
    'text/x-chdr' => [%w(h), %w(text/x-csrc)],
    'text/x-cmake' => [%w(cmake), %w()],
    'text/x-csharp' => [%w(cs), %w(text/x-csrc)],
    'text/x-csrc' => [%w(c), %w(text/plain)],
    'text/x-dcl' => [%w(dcl), %w(text/plain)],
    'text/x-dsl' => [%w(dsl), %w(text/plain)],
    'text/x-dsrc' => [%w(d), %w(text/x-csrc)],
    'text/x-eiffel' => [%w(e eif), %w(text/plain)],
    'text/x-emacs-lisp' => [%w(el), %w(text/plain)],
    'text/x-erlang' => [%w(erl), %w(text/plain)],
    'text/x-fortran' => [%w(f f90 f95 for), %w(text/plain)],
    'text/x-gettext-translation' => [%w(po), %w(text/plain)],
    'text/x-gettext-translation-template' => [%w(pot), %w(text/plain)],
    'text/x-google-video-pointer' => [%w(gvp), %w()],
    'text/x-haskell' => [%w(hs), %w(text/plain)],
    'text/x-iMelody' => [%w(ime imy), %w()],
    'text/x-idl' => [%w(idl), %w(text/plain)],
    'text/x-iptables' => [%w(iptables), %w(text/plain)],
    'text/x-java' => [%w(java), %w(text/x-csrc)],
    'text/x-ldif' => [%w(ldif), %w(text/plain)],
    'text/x-lilypond' => [%w(ly), %w(text/plain)],
    'text/x-literate-haskell' => [%w(lhs), %w(text/plain)],
    'text/x-log' => [%w(log), %w(text/plain)],
    'text/x-lua' => [%w(lua), %w(application/x-executable text/plain)],
    'text/x-matlab' => [%w(m), %w(text/plain)],
    'text/x-microdvd' => [%w(sub), %w(text/plain)],
    'text/x-moc' => [%w(moc), %w(text/plain)],
    'text/x-mof' => [%w(mof), %w(text/x-csrc)],
    'text/x-mpsub' => [%w(sub), %w(text/plain)],
    'text/x-mrml' => [%w(mrl mrml), %w()],
    'text/x-ms-regedit' => [%w(reg), %w(text/plain)],
    'text/x-mup' => [%w(mup not), %w(text/plain)],
    'text/x-nfo' => [%w(nfo), %w(text/x-readme)],
    'text/x-objcsrc' => [%w(m), %w(text/x-csrc)],
    'text/x-ocaml' => [%w(ml mli), %w()],
    'text/x-ocl' => [%w(ocl), %w(text/plain)],
    'text/x-opml+xml' => [%w(opml), %w(application/xml)],
    'text/x-pascal' => [%w(p pas), %w(text/plain)],
    'text/x-patch' => [%w(diff patch), %w(text/plain)],
    'text/x-python' => [%w(py), %w(application/x-executable text/plain)],
    'text/x-rpm-spec' => [%w(spec), %w(text/plain)],
    'text/x-scheme' => [%w(scm), %w(text/plain)],
    'text/x-setext' => [%w(etx), %w(text/plain)],
    'text/x-sql' => [%w(sql), %w(text/plain)],
    'text/x-ssa' => [%w(ass ssa), %w(text/plain)],
    'text/x-subviewer' => [%w(sub), %w(text/plain)],
    'text/x-tcl' => [%w(tcl tk), %w(text/plain)],
    'text/x-tex' => [%w(cls dtx ins latex ltx sty tex), %w(text/plain)],
    'text/x-texinfo' => [%w(texi texinfo), %w(text/plain)],
    'text/x-troff-me' => [%w(me), %w(text/plain)],
    'text/x-troff-mm' => [%w(mm), %w(text/plain)],
    'text/x-troff-ms' => [%w(ms), %w(text/plain)],
    'text/x-txt2tags' => [%w(t2t), %w(text/plain)],
    'text/x-uil' => [%w(uil), %w(text/plain)],
    'text/x-uri' => [%w(uri url), %w(text/plain)],
    'text/x-vala' => [%w(vala vapi), %w(text/x-csrc)],
    'text/x-vhdl' => [%w(vhd vhdl), %w(text/plain)],
    'text/x-xmi' => [%w(xmi), %w(application/xml)],
    'text/x-xslfo' => [%w(fo xslfo), %w(application/xml)],
    'video/3gpp' => [%w(3g2 3ga 3gp 3gpp), %w(video/mp4)],
    'video/annodex' => [%w(axv), %w(application/annodex)],
    'video/dv' => [%w(dv), %w()],
    'video/mp4' => [%w(m4v mp4), %w()],
    'video/mpeg' => [%w(m2t mp2 mpe mpeg mpg vob), %w()],
    'video/ogg' => [%w(ogv), %w(application/ogg)],
    'video/quicktime' => [%w(moov mov qt qtvr), %w()],
    'video/vivo' => [%w(viv vivo), %w()],
    'video/vnd.rn-realvideo' => [%w(rv rvx), %w()],
    'video/x-flic' => [%w(flc fli), %w()],
    'video/x-flv' => [%w(flv), %w()],
    'video/x-matroska' => [%w(mkv), %w(application/x-matroska)],
    'video/x-mng' => [%w(mng), %w()],
    'video/x-ms-asf' => [%w(asf), %w()],
    'video/x-ms-wmv' => [%w(wmv), %w(video/x-ms-asf)],
    'video/x-msvideo' => [%w(avi divx), %w()],
    'video/x-nsv' => [%w(nsv), %w()],
    'video/x-ogm+ogg' => [%w(ogm), %w(video/ogg)],
    'video/x-sgi-movie' => [%w(movie), %w()],
    'video/x-theora+ogg' => [%w(ogg), %w(video/ogg)],
    'x-epoc/x-sisx-app' => [%w(sisx), %w()],
  }
  MAGIC = [
    ['application/vnd.stardivision.writer', [[2089, "StarWriter"]]],
    ['application/docbook+xml', [[0, "<?xml", [[0..100, "-//OASIS//DTD DocBook XML"], [0..100, "-//KDE//DTD DocBook XML"]]]]],
    ['image/x-eps', [[0, "%!", [[15, "EPS"]]], [0, "\x04%!", [[16, "EPS"]]]]],
    ['image/svg+xml', [[0..256, "<!DOCTYPE svg"], [0..256, "<svg"]]],
    ['application/vnd.corel-draw', []],
    ['image/x-niff', [[0, "IIN1"]]],
    ['application/x-mozilla-bookmarks', [[0..64, "<!DOCTYPE NETSCAPE-Bookmark-file-1>"]]],
    ['application/x-fictionbook+xml', [[0..256, "<FictionBook"]]],
    ['audio/x-vorbis+ogg', [[0, "OggS", [[28, "\x01vorbis"]]]]],
    ['image/x-kodak-kdc', [[242, "EASTMAN KODAK COMPANY"]]],
    ['application/x-xliff', [[0..256, "<xliff"]]],
    ['audio/x-flac+ogg', [[0, "OggS", [[28, "fLaC"]]], [0, "OggS", [[28, "\x7FFLAC"]]]]],
    ['audio/x-speex+ogg', [[0, "OggS", [[28, "Speex  "]]]]],
    ['application/x-php', [[0..64, "<?php"]]],
    ['video/x-ogm+ogg', [[0, "OggS", [[29, "video"]]]]],
    ['video/x-theora+ogg', [[0, "OggS", [[28, "\x80theora"]]]]],
    ['application/x-pak', [[0, "PACK"]]],
    ['application/prs.plucker', [[60, "DataPlkr"]]],
    ['application/rss+xml', [[0..256, "<rss "], [0..256, "<RSS "]]],
    ['text/x-opml+xml', [[0..256, "<opml "]]],
    ['application/vnd.apple.mpegurl', [[0..128, "#EXT-X-TARGETDURATION"]]],
    ['application/atom+xml', [[0..256, "<feed "]]],
    ['application/vnd.ms-wpl', [[0..256, "<?wpl"]]],
    ['text/x-txt2tags', [[0, "%!postproc"], [0, "%!encoding"]]],
    ['application/msword', [[0, "1\xBE\x00\x00"], [0, "PO^Q`"], [0, "\xFE7\x00#"], [0, "\xDB\xA5-\x00\x00\x00"], [2112, "MSWordDoc"], [2108, "MSWordDoc"], [2112, "Microsoft Word document data"], [546, "bjbj"], [546, "jbjb"]]],
    ['application/x-font-type1', [[0, "LWFN"], [65, "LWFN"], [0, "%!PS-AdobeFont-1."], [6, "%!PS-AdobeFont-1."], [0, "%!FontType1-1."], [6, "%!FontType1-1."]]],
    ['application/x-quicktime-media-link', [[0, "<?xml", [[0..64, "<?quicktime"]]], [0, "RTSPtext"], [0, "rtsptext"], [0, "SMILtext"]]],
    ['application/smil', [[0..256, "<smil"]]],
    ['audio/x-ms-asx', [[0, "ASF "], [0..64, "<ASX"], [0..64, "<asx"], [0..64, "<Asx"]]],
    ['image/x-icns', [[0, "icns"]]],
    ['application/gnunet-directory', [[0, "\x89GND\r\n\x1A\n"]]],
    ['application/x-t602', [[0, "@CT 0"], [0, "@CT 1"], [0, "@CT 2"]]],
    ['application/vnd.emusic-emusic_package', [[0, "nF7YLao"]]],
    ['video/x-sgi-movie', [[0, "MOVI"]]],
    ['application/sdp', [[0, "v=", [[0..256, "s="]]]]],
    ['video/x-nsv', [[0, "NSVf"]]],
    ['video/x-msvideo', [[0, "RIFF", [[8, "AVI "]]]]],
    ['application/x-netshow-channel', [[0, "[Address]"]]],
    ['video/x-ms-asf', [[0, "0&\xB2u"], [0, "[Reference]"]]],
    ['application/x-hwp', [[0, "HWP Document File"]]],
    ['video/x-flic', [[0, "\x11\xAF"], [0, "\x12\xAF"]]],
    ['application/vnd.oasis.opendocument.text', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.text"]]]]]]],
    ['application/vnd.oasis.opendocument.text-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.text-template"]]]]]]],
    ['application/vnd.oasis.opendocument.text-web', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.text-web"]]]]]]],
    ['application/vnd.oasis.opendocument.text-master', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.text-master"]]]]]]],
    ['application/vnd.oasis.opendocument.graphics', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.graphics"]]]]]]],
    ['application/vnd.oasis.opendocument.graphics-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.graphics-template"]]]]]]],
    ['application/vnd.oasis.opendocument.presentation', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.presentation"]]]]]]],
    ['application/vnd.oasis.opendocument.presentation-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.presentation-template"]]]]]]],
    ['application/vnd.oasis.opendocument.spreadsheet', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.spreadsheet"]]]]]]],
    ['application/vnd.oasis.opendocument.spreadsheet-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.spreadsheet-template"]]]]]]],
    ['application/vnd.oasis.opendocument.chart', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.chart"]]]]]]],
    ['application/vnd.oasis.opendocument.chart-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.chart-template"]]]]]]],
    ['application/vnd.oasis.opendocument.formula', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.formula"]]]]]]],
    ['application/vnd.oasis.opendocument.formula-template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.formula-template"]]]]]]],
    ['application/vnd.oasis.opendocument.image', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.oasis.opendocument.image"]]]]]]],
    ['application/vnd.symbian.install', [[8, "\x19\x04\x00\x10"]]],
    ['x-epoc/x-sisx-app', [[0, "z\x1A \x10"]]],
    ['application/vnd.wordperfect', [[1, "WPC"]]],
    ['application/x-spss-por', [[40, "ASCII SPSS PORT FILE"]]],
    ['application/x-spss-sav', [[0, "$FL2"]]],
    ['application/x-xbel', [[0..256, "<!DOCTYPE xbel"]]],
    ['application/x-7z-compressed', [[0, "7z\xBC\xAF'\x1C"]]],
    ['application/x-abiword', [[0..256, "<abiword"], [0..256, "<!DOCTYPE abiword"]]],
    ['application/x-aportisdoc', [[60, "TEXtREAd"], [60, "TEXtTlDc"]]],
    ['application/x-applix-spreadsheet', [[0, "*BEGIN SPREADSHEETS"], [0, "*BEGIN", [[7, "SPREADSHEETS"]]]]],
    ['application/x-applix-word', [[0, "*BEGIN", [[7, "WORDS"]]]]],
    ['application/x-arc', []],
    ['image/x-quicktime', [[4, "idat"]]],
    ['application/x-arj', [[0, "`\xEA"]]],
    ['application/x-awk', [[0, "#!/bin/gawk"], [0, "#! /bin/gawk"], [0, "#!/usr/bin/gawk"], [0, "#! /usr/bin/gawk"], [0, "#!/usr/local/bin/gawk"], [0, "#! /usr/local/bin/gawk"], [0, "#!/bin/awk"], [0, "#! /bin/awk"], [0, "#!/usr/bin/awk"], [0, "#! /usr/bin/awk"]]],
    ['application/x-bittorrent', [[0, "d8:announce"]]],
    ['application/x-blender', [[0, "BLENDER"]]],
    ['application/x-bzip', [[0, "BZh"]]],
    ['application/x-cdrdao-toc', [[0, "CD_ROM\n"], [0, "CD_DA\n"], [0, "CD_ROM_XA\n"], [0, "CD_TEXT "], [0, "CATALOG \"", [[22, "\""]]]]],
    ['application/x-chess-pgn', [[0, "[Event "]]],
    ['application/x-compress', [[0, "\x1F\x9D"]]],
    ['application/x-core', [[0, "\x7FELF", [[5, "\x01", [[16, "\x04\x00"]]]]], [0, "\x7FELF", [[5, "\x02", [[16, "\x00\x04"]]]]], [0, "Core\x01"], [0, "Core\x02"]]],
    ['application/x-cpio', [[0, "\xC7q"], [0, "070701"], [0, "070702"], [0, "q\xC7"]]],
    ['video/quicktime', [[12, "mdat"], [4, "mdat"], [4, "moov"], [4, "ftypqt"]]],
    ['application/x-deb', [[0, "!<arch>", [[8, "debian"]]]]],
    ['application/x-desktop', [[0..32, "[Desktop Entry]"], [0, "[Desktop Action"], [0, "[KDE Desktop Entry]"], [0, "# Config File"], [0, "# KDE Config File"]]],
    ['application/vnd.ms-excel', [[2080, "Microsoft Excel 5.0 Worksheet"]]],
    ['application/x-dia-diagram', [[5..100, "<dia:"]]],
    ['application/x-dvi', [[0, "\xF7\x02"]]],
    ['video/mpeg', [[0, "G?\xFF\x10"], [0, "\x00\x00\x01\xB3"], [0, "\x00\x00\x01\xBA"]]],
    ['application/x-fluid', [[0, "# data file for the Fltk"], [0, "version"], [0, "header_name"], [0, "code_name"]]],
    ['application/vnd.ms-cab-compressed', [[0, "MSCF\x00\x00\x00\x00"]]],
    ['application/x-font-bdf', [[0, "STARTFONT "]]],
    ['application/x-font-dos', [[0, "\xFFFON"], [7, "\x00EGA"], [7, "\x00VID"]]],
    ['application/x-font-framemaker', [[0, "<MakerScreenFont"]]],
    ['application/x-font-libgrx', [[0, "\x14\x02Y\x19"]]],
    ['application/x-font-linux-psf', [[0, "6\x04"]]],
    ['application/x-font-pcf', [[0, "\x01fcp"]]],
    ['application/x-font-otf', [[0, "OTTO"]]],
    ['application/x-font-speedo', [[0, "D1.0\r"]]],
    ['application/x-font-sunos-news', [[0, "StartFont"], [0, "\x13z)"], [8, "\x13z+"]]],
    ['application/x-font-tex', [[0, "\xF7\x83"], [0, "\xF7Y"], [0, "\xF7\xCA"]]],
    ['application/x-font-tex-tfm', [[2, "\x00\x11"], [2, "\x00\x12"]]],
    ['application/x-font-ttf', [[0, "FFIL"], [65, "FFIL"], [0, "\x00\x01\x00\x00\x00"]]],
    ['application/x-font-ttx', [[0..256, "<ttFont sfntVersion=\"\\x00\\x01\\x00\\x00\" ttLibVersion=\""]]],
    ['application/x-font-vfont', [[0, "FONT"]]],
    ['application/x-frame', [[0, "<MakerFile"], [0, "<MIFFile"], [0, "<MakerDictionary"], [0, "<MakerScreenFon"], [0, "<MML"], [0, "<Book"], [0, "<Maker"]]],
    ['application/x-gdbm', [[0, "\x13W\x9A\xCE"], [0, "\xCE\x9AW\x13"], [0, "GDBM"]]],
    ['application/x-glade', [[0..256, "<glade-interface"]]],
    ['application/x-gmc-link', [[0..32, "URL:"]]],
    ['application/x-gnumeric', [[0..64, "gmr:Workbook"], [0..64, "gnm:Workbook"]]],
    ['application/x-gtktalog', [[4, "gtktalog "]]],
    ['application/x-gzip', [[0, "\x1F\x8B"]]],
    ['application/x-ipod-firmware', [[0, "S T O P"]]],
    ['application/x-java', [[0, "\xCA\xFE\xBA\xBE"]]],
    ['application/x-java-jnlp-file', [[0..256, "<jnlp"]]],
    ['application/x-java-keystore', [[0, "\xED\xFE\xED\xFE"]]],
    ['application/x-java-jce-keystore', [[0, "\xCE\xCE\xCE\xCE"]]],
    ['application/x-java-pack200', [[0, "\xCA\xFE\xD0\r"]]],
    ['application/x-karbon', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-karbon\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-karbon"]]]]]]],
    ['application/x-kchart', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kchart\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kchart"]]]]]]],
    ['application/x-kformula', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kformula\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kformula"]]]]]]],
    ['application/x-killustrator', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-killustrator\x04\x06"]]]]]]],
    ['application/x-kivio', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kivio\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kivio"]]]]]]],
    ['application/x-kontour', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kontour\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kontour"]]]]]]],
    ['application/x-kpresenter', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kpresenter\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kpresenter"]]]]]]],
    ['application/x-krita', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-krita\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-krita"]]]]]]],
    ['application/x-kspread', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kspread\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kspread"]]]]]]],
    ['application/x-kspread-crypt', [[0, "\r\x1A'\x02"]]],
    ['application/x-ksysv-package', [[4, "KSysV", [[15, "\x01"]]]]],
    ['application/x-kword', [[0, "\x1F\x8B", [[10, "KOffice", [[18, "application/x-kword\x04\x06"]]]]], [0, "PK\x03\x04", [[30, "mimetype", [[38, "application/x-kword"]]]]]]],
    ['application/x-kword-crypt', [[0, "\r\x1A'\x01"]]],
    ['application/x-lha', [[2, "-lh -"], [2, "-lh0-"], [2, "-lh1-"], [2, "-lh2-"], [2, "-lh3-"], [2, "-lh4-"], [2, "-lh5-"], [2, "-lh40-"], [2, "-lhd-"], [2, "-lz4-"], [2, "-lz5-"], [2, "-lzs-"]]],
    ['application/x-lyx', [[0, "#LyX"]]],
    ['application/x-lzip', [[0, "LZIP"]]],
    ['application/x-lzop', [[0, "\x89LZO\x00\r\n\x1A\n"]]],
    ['application/x-macbinary', [[102, "mBIN"]]],
    ['application/x-matroska', [[8, "matroska"]]],
    ['application/mxf', [[0..256, "\x06\x0E+4\x02\x05\x01\x01\r\x01\x02\x01\x01\x02"]]],
    ['application/vnd.ms-access', [[0, "\x00\x01\x00\x00Standard Jet DB"]]],
    ['application/x-ms-dos-executable', [[0, "MZ"]]],
    ['application/x-mswinurl', [[1, "InternetShortcut"], [1, "DEFAULT", [[11, "BASEURL="]]]]],
    ['application/x-nautilus-link', [[0..32, "<nautilus_object nautilus_link"]]],
    ['application/x-object', [[0, "\x7FELF", [[5, "\x01", [[16, "\x01\x00"]]]]], [0, "\x7FELF", [[5, "\x02", [[16, "\x00\x01"]]]]]]],
    ['application/annodex', [[0, "OggS", [[28, "fishead\x00", [[56..512, "CMML\x00\x00\x00\x00"]]]]]]],
    ['video/annodex', [[0, "OggS", [[28, "fishead\x00", [[56..512, "CMML\x00\x00\x00\x00"]]]]]]],
    ['audio/annodex', [[0, "OggS", [[28, "fishead\x00", [[56..512, "CMML\x00\x00\x00\x00"]]]]]]],
    ['application/ogg', [[0, "OggS"]]],
    ['audio/ogg', [[0, "OggS"]]],
    ['video/ogg', [[0, "OggS"]]],
    ['application/vnd.lotus-1-2-3', [[0, "\x00\x00\x02\x00\x06\x04\x06\x00\b\x00\x00\x00\x00\x00"]]],
    ['application/x-go-sgf', [[0, "(;FF[3]"], [0, "(;FF[4]"]]],
    ['video/x-flv', [[0, "FLV"]]],
    ['audio/x-speex', [[0, "Speex"]]],
    ['application/x-gedcom', [[0, "0 HEAD"]]],
    ['application/x-cisco-vpn-settings', [[0, "[main]", [[0..256, "AuthType="]]]]],
    ['application/x-ole-storage', [[0, "\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1"], [0, "\xD0\xCF\x11\xE0"]]],
    ['application/x-oleo', [[31, "Oleo"]]],
    ['application/vnd.iccprofile', [[36, "acsp"]]],
    ['application/x-par2', [[0, "PAR2"]]],
    ['application/x-pef-executable', [[0, "Joy!"]]],
    ['application/x-perl', [[0, "eval \"exec /usr/local/bin/perl"], [1..16, "/bin/perl"], [1..16, "/bin/env perl"]]],
    ['application/rtf', [[0, "{\\rtf"]]],
    ['application/x-pocket-word', [[0, "{\\pwi"]]],
    ['application/x-python-bytecode', [[0, "\x99N\r\n"]]],
    ['application/epub+zip', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/epub+zip"]]]]]]],
    ['application/x-rar', [[0, "Rar!"]]],
    ['video/dv', []],
    ['application/x-alz', [[0, "ALZ"]]],
    ['application/x-rpm', [[0, "\xED\xAB\xEE\xDB"]]],
    ['text/xmcd', [[0, "# xmcd"]]],
    ['application/x-sc', [[38, "Spreadsheet"]]],
    ['application/x-sharedlib', [[0, "\x7FELF", [[5, "\x01", [[16, "\x03\x00"]]]]], [0, "\x7FELF", [[5, "\x02", [[16, "\x00\x03"]]]]], [0, "\x83\x01"]]],
    ['application/x-shellscript', [[10, "# This is a shell archive"], [1..16, "/bin/bash"], [1..16, "/bin/nawk"], [1..16, "/bin/zsh"], [1..16, "/bin/sh"], [1..16, "/bin/ksh"], [0, "#!/usr/bin/env sh"], [0, "#!/usr/bin/env bash"], [0, "#!/usr/bin/env zsh"], [0, "#!/usr/bin/env ksh"]]],
    ['application/x-shockwave-flash', [[0, "FWS"], [0, "CWS"]]],
    ['application/x-shorten', [[0, "ajkg"]]],
    ['image/x-skencil', [[0, "##Sketch"]]],
    ['application/x-stuffit', [[0, "StuffIt "], [0, "SIT!"]]],
    ['application/x-subrip', [[0, "1", [[0..256, " --> "]]]]],
    ['application/x-sami', [[0..256, "<SAMI>"]]],
    ['text/x-microdvd', [[0, "{1}"], [0, "{0}"], [0..6, "}{"]]],
    ['text/x-mpsub', [[0..256, "FORMAT="]]],
    ['text/x-ssa', [[0..256, "[Script Info]"], [0..256, "Dialogue: "]]],
    ['text/x-subviewer', [[0, "[INFORMATION]"]]],
    ['text/x-iMelody', [[0, "BEGIN:IMELODY"]]],
    ['application/x-smaf', [[0, "MMMD"]]],
    ['text/x-mrml', [[0, "<mrml "]]],
    ['audio/x-xmf', [[0, "XMF_"], [0, "XMF_2.00\x00\x00\x00\x02"]]],
    ['application/x-tar', [[257, "ustar\x00"], [257, "ustar  \x00"]]],
    ['application/x-tgif', [[0, "%TGIF"]]],
    ['text/troff', [[0, ".\\\""], [0, "'\\\""], [0, "'.\\\""], [0, "\\\""]]],
    ['application/x-xz', [[0, "\xFD7zXZ\x00"]]],
    ['application/x-zoo', [[20, "\xDC\xA7\xC4\xFD"]]],
    ['text/x-iptables', [[0..256, "/etc/sysconfig/iptables"], [0..256, "*filter", [[0..256, ":INPUT", [[0..256, ":FORWARD", [[0..256, ":OUTPUT"]]]]]]], [0..256, "-A INPUT", [[0..256, "-A FORWARD", [[0..256, "-A OUTPUT"]]]]], [0..256, "-P INPUT", [[0..256, "-P FORWARD", [[0..256, "-P OUTPUT"]]]]]]],
    ['audio/ac3', [[0, "\vw"]]],
    ['audio/AMR', [[0, "#!AMR\n"], [0, "#!AMR_MC1.0\n"]]],
    ['audio/AMR-WB', [[0, "#!AMR-WB\n"], [0, "#!AMR-WB_MC1.0\n"]]],
    ['text/x-tex', [[1, "documentclass"]]],
    ['audio/prs.sid', [[0, "PSID"]]],
    ['audio/x-adpcm', [[0, ".snd", [[12, "\x00\x00\x00\x17"]]], [0, ".sd\x00", [[12, "\x01\x00\x00\x00"], [12, "\x02\x00\x00\x00"], [12, "\x03\x00\x00\x00"], [12, "\x04\x00\x00\x00"], [12, "\x05\x00\x00\x00"], [12, "\x06\x00\x00\x00"], [12, "\a\x00\x00\x00"], [12, "\x17\x00\x00\x00"]]]]],
    ['audio/x-aifc', [[8, "AIFC"]]],
    ['audio/x-aiff', [[8, "AIFF"], [8, "AIFC"], [8, "8SVX"]]],
    ['audio/x-ape', [[0, "MAC "]]],
    ['audio/x-it', [[0, "IMPM"]]],
    ['audio/x-flac', [[0, "fLaC"]]],
    ['audio/x-wavpack', [[0, "wvpk"]]],
    ['audio/x-wavpack-correction', [[0, "wvpk"]]],
    ['audio/midi', [[0, "MThd"]]],
    ['audio/x-mo3', [[0, "MO3"]]],
    ['audio/mp4', [[4, "ftypM4A"]]],
    ['video/mp4', [[4, "ftypisom"], [4, "ftypmp42"], [4, "ftypMSNV"], [4, "ftypM4V "]]],
    ['audio/x-m4b', [[4, "ftypM4B"]]],
    ['video/3gpp', [[4, "ftyp3gp"]]],
    ['audio/mpeg', [[0, "\x00\x00\xFF\xFB"], [0, "ID3"]]],
    ['audio/x-mpegurl', [[0, "#EXTM3U"]]],
    ['application/postscript', [[0, "\x04%!"], [0, "%!"]]],
    ['application/pgp-signature', [[0, "-----BEGIN PGP SIGNED MESSAGE-----"], [0, "-----BEGIN PGP SIGNATURE-----"]]],
    ['audio/x-psf', [[0, "PSF"]]],
    ['audio/x-musepack', [[0, "MP+"]]],
    ['application/vnd.rn-realmedia', [[0, ".RMF"]]],
    ['text/x-rpm-spec', [[0, "Summary: "], [0, "%define "]]],
    ['audio/x-s3m', [[44, "SCRM"]]],
    ['audio/x-scpls', [[0, "[playlist]"], [0, "[Playlist]"], [0, "[PLAYLIST]"]]],
    ['audio/x-wav', [[8, "WAVE"], [8, "WAV "]]],
    ['audio/x-xi', [[0, "Extended Intrument:"]]],
    ['audio/x-xm', [[0, "Extended Module:"]]],
    ['audio/x-tta', [[0, "TTA1"]]],
    ['image/bmp', [[0, "BM", [[14, "\f"], [14, "@"], [14, "("]]]]],
    ['image/gif', [[0, "GIF8"]]],
    ['image/jpeg', [[0, "\xFF\xD8\xFF"], [0, "\xFF\xD8"]]],
    ['image/jp2', [[4, "jP"], [0, "\xFFO\xFFQ\x00"], [3, "\fjP "]]],
    ['image/openraster', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "image/openraster"]]]]]]],
    ['image/x-dds', [[0, "DDS"]]],
    ['image/x-xcursor', [[0, "Xcur"]]],
    ['image/x-exr', [[0, "v/1\x01"]]],
    ['image/x-canon-crw', [[0, "II\x1A\x00\x00\x00HEAPCCDR"]]],
    ['image/x-fuji-raf', [[0, "FUJIFILMCCD-RAW "]]],
    ['application/pgp-keys', [[0, "-----BEGIN PGP PUBLIC KEY BLOCK-----"], [0, "-----BEGIN PGP PRIVATE KEY BLOCK-----"], [0, "\x95\x01"], [0, "\x95\x00"], [0, "\x99\x00"], [0, "\x99\x01"]]],
    ['image/x-minolta-mrw', [[0, "\x00MRM"]]],
    ['image/x-olympus-orf', [[0, "IIRO\b\x00\x00\x00"]]],
    ['image/x-panasonic-raw', [[0, "IIU\x00\b\x00\x00\x00"]]],
    ['image/x-sigma-x3f', [[0, "FOVb"]]],
    ['image/png', [[0, "\x89PNG"]]],
    ['application/pgp-encrypted', [[0, "-----BEGIN PGP MESSAGE-----"]]],
    ['image/tiff', [[0, "MM\x00*"], [0, "II*\x00"]]],
    ['image/vnd.dxf', [[0..64, "\nHEADER\n"], [0..64, "\r\nHEADER\r\n"]]],
    ['image/vnd.ms-modi', [[0, "EP*\x00"]]],
    ['image/x-applix-graphics', [[0, "*BEGIN", [[7, "GRAPHICS"]]]]],
    ['application/dicom', [[128, "DICM"]]],
    ['audio/x-iriver-pla', [[4, "iriver UMS PLA"]]],
    ['image/x-dib', [[0, "(\x00\x00\x00"]]],
    ['image/vnd.djvu', [[0, "AT&TFORM", [[12, "DJVM"], [12, "DJVU"]]], [0, "FORM", [[8, "DJVM"], [8, "DJVU"]]]]],
    ['image/dpx', [[0, "SDPX"]]],
    ['application/xspf+xml', [[0..64, "<playlist version=\"1"]]],
    ['image/fits', [[0, "SIMPLE  ="]]],
    ['image/x-fpx', [[0, "FPix"]]],
    ['image/vnd.microsoft.icon', [[0, "\x00\x00\x01\x00", [[5, "\x00"]]]]],
    ['application/vnd.ms-tnef', [[0, "x\x9F>\""]]],
    ['application/pdf', [[0, "%PDF-"]]],
    ['image/x-pcx', [[0, "\n", [[1, "\x00"], [1, "\x02"], [1, "\x03"], [1, "\x05"]]]]],
    ['image/x-portable-bitmap', [[0, "P1", [[2, "\n", [[3, "#"]]]]], [0, "P4", [[2, "\n", [[3, "#"]]]]]]],
    ['image/x-portable-graymap', [[0, "P2", [[2, "\n", [[3, "#"]]]]], [0, "P5", [[2, "\n", [[3, "#"]]]]]]],
    ['image/x-portable-pixmap', [[0, "P3", [[2, "\n", [[3, "#"]]]]], [0, "P6", [[2, "\n", [[3, "#"]]]]]]],
    ['image/vnd.adobe.photoshop', []],
    ['image/x-sun-raster', [[0, "Y\xA6j\x95"]]],
    ['text/x-lua', [[0, "/bin/lua"], [0, "/bin/env lua"]]],
    ['image/x-win-bitmap', [[0, "\x00\x00\x02\x00", [[5, "\x00"]]]]],
    ['application/x-navi-animation', [[0, "RIFF", [[8, "ACON"]]]]],
    ['image/x-emf', [[0, "\x01\x00\x00\x00", [[40, " EMF", [[44, "\x00\x00\x01\x00", [[58, "\x00\x00"]]]]]]]]],
    ['image/x-wmf', [[0, "\xD7\xCD\xC6\x9A", [[22, "\x01\x00", [[24, "\t\x00"]]]]], [0, "\x01\x00", [[2, "\t\x00"]]]]],
    ['image/x-xcf', [[0, "gimp xcf file"]]],
    ['image/x-xfig', [[0, "#FIG"]]],
    ['image/x-xpixmap', [[0, "/* XPM"]]],
    ['message/news', [[0, "Article"], [0, "Path:"], [0, "Xref:"]]],
    ['message/rfc822', [[0, "#! rnews"], [0, "Forward to"], [0, "From:"], [0, "N#! rnews"], [0, "Pipe to"], [0, "Received:"], [0, "Relay-Version:"], [0, "Return-Path:"], [0, "Return-path:"], [0, "Subject: "]]],
    ['text/calendar', [[0, "BEGIN:VCALENDAR"], [0, "begin:vcalendar"]]],
    ['text/directory', [[0, "BEGIN:VCARD"], [0, "begin:vcard"]]],
    ['application/metalink+xml', [[0..256, "<metalink"]]],
    ['text/x-python', [[0, "#!/bin/python"], [0, "#! /bin/python"], [0, "eval \"exec /bin/python"], [0, "#!/usr/bin/python"], [0, "#! /usr/bin/python"], [0, "eval \"exec /usr/bin/python"], [0, "#!/usr/local/bin/python"], [0, "#! /usr/local/bin/python"], [0, "eval \"exec /usr/local/bin/python"], [1..16, "/bin/env python"]]],
    ['text/plain', [[0, "This is TeX,"], [0, "This is METAFONT,"]]],
    ['application/x-it87', [[0, "IT8.7"]]],
    ['application/mathematica', [[0, "(************** Content-type: application/mathematica"], [100..256, "This notebook can be used on any computer system with Mathematica"], [10..256, "This is a Mathematica Notebook file.  It contains ASCII text"]]],
    ['application/mac-binhex40', [[11, "must be converted with BinHex"]]],
    ['text/spreadsheet', [[0, "ID;"]]],
    ['text/x-matlab', [[0, "function"]]],
    ['text/vnd.sun.j2me.app-descriptor', [[0, "MIDlet-"]]],
    ['application/x-ace', [[7, "**ACE**"]]],
    ['text/x-patch', [[0, "diff\t"], [0, "diff "], [0, "***\t"], [0, "*** "], [0, "=== "], [0, "--- "], [0, "Only in\t"], [0, "Only in "], [0, "Common subdirectories: "], [0, "Index:"]]],
    ['text/x-emacs-lisp', [[0, "\n("], [0, ";ELC\x13\x00\x00\x00"]]],
    ['text/html', [[0..256, "<!DOCTYPE HTML"], [0..256, "<!doctype html"], [0..256, "<HEAD"], [0..256, "<head"], [0..256, "<TITLE"], [0..256, "<title"], [0..256, "<HTML"], [0..256, "<html"], [0..256, "<SCRIPT"], [0..256, "<script"], [0, "<BODY"], [0, "<body"], [0, "<!--"], [0, "<h1"], [0, "<H1"], [0, "<!doctype HTML"], [0, "<!DOCTYPE html"]]],
    ['text/x-google-video-pointer', [[0, "#.download.the.free.Google.Video.Player"], [0, "# download the free Google Video Player"]]],
    ['text/x-ldif', [[0, "dn: cn="], [0, "dn: mail="]]],
    ['text/x-makefile', [[0, "#!/usr/bin/make"], [0, "#! /usr/bin/make"]]],
    ['text/x-ms-regedit', [[0, "REGEDIT"], [0, "Windows Registry Editor Version 5.00"], [0, "\xFF\xFEW\x00i\x00n\x00d\x00o\x00w\x00s\x00 \x00R\x00e\x00g\x00i\x00s\x00t\x00r\x00y\x00 \x00E\x00d\x00i\x00t\x00o\x00r\x00"]]],
    ['text/x-mup', [[0, "//!Mup"]]],
    ['text/vnd.graphviz', [[0, "digraph "], [0, "strict digraph "], [0, "graph "], [0, "strict graph "]]],
    ['application/x-archive', [[0, "<ar>"], [0, "!<arch>"]]],
    ['audio/x-riff', [[0, "RIFF"]]],
    ['application/xml', [[0, "<?xml"], [0, "<!--"]]],
    ['application/zip', [[0, "PK\x03\x04"]]],
    ['audio/basic', [[0, ".snd"]]],
    ['application/x-executable', [[0, "\x7FELF", [[5, "\x01", [[16, "\x02\x00"]]]]], [0, "\x7FELF", [[5, "\x02", [[16, "\x00\x02"]]]]], [0, "MZ"], [0, "\x1CR"], [0, "\x10\x01"], [0, "\x11\x01"], [0, "\x83\x01"]]],
    ['text/x-objcsrc', [[0, "#import"]]],
    ['text/x-csrc', [[0, "/*"], [0, "//"], [0, "#include"]]],
    ['text/x-vhdl', [[0, "--"]]],
    ['application/mbox', [[0, "From "]]],
    ['text/x-matlab', [[0, "%"]]],
    ['image/x-tga', [[1, "\x01\x01"], [1, "\x019"], [1, "\x00\x03"], [1, "\x00\n"], [1, "\x00\v"], [1, "\x00\x02"]]],
    ['text/x-tex', [[0, "%"]]],
    ['application/vnd.sun.xml.impress.template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.impress"]]]]]]],
    ['application/x-dar', [[0, "\x00\x00\x00{"]]],
    ['application/vnd.sun.xml.writer.template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.writer"]]]]]]],
    ['application/vnd.sun.xml.writer.global', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.writer"]]]]]]],
    ['application/vnd.sun.xml.writer', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.writer"]]]]]]],
    ['application/vnd.sun.xml.math', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.math"]]]]]]],
    ['application/x-csh', [[1..16, "/bin/tcsh"], [1..16, "/bin/csh"], [0, "#!/usr/bin/env csh"], [0, "#!/usr/bin/env tcsh"]]],
    ['application/vnd.sun.xml.impress', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.impress"]]]]]]],
    ['application/vnd.sun.xml.draw.template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.draw"]]]]]]],
    ['application/vnd.sun.xml.draw', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.draw"]]]]]]],
    ['application/vnd.sun.xml.calc.template', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.calc"]]]]]]],
    ['application/vnd.sun.xml.calc', [[0, "PK\x03\x04", [[30, "mimetype", [[38, "application/vnd.sun.xml.calc"]]]]]]],
    ['application/x-sqlite3', [[0, "SQLite format 3"]]],
    ['application/x-sqlite2', [[0, "** This file contains an SQLite"]]],
    ['application/x-ruby', [[1..16, "/bin/env ruby"], [1..16, "/bin/ruby"]]],
  ]
end
